

const {ccclass, property, requireComponent} = cc._decorator;

@ccclass
export default class NewClass extends cc.Component {


    @property(cc.Node)
    node1: cc.Node = null;

    @property(cc.Node)
    node2: cc.Node = null;

    @property(cc.Node)
    node3: cc.Node = null;

    @property(false)
    localTest: boolean = false;

    @property("")
    clientTestVersion: string = "1.0.0";

    @property(cc.Label)
    testVersion: cc.Label = null;

    start () {

        // cc.fx.AudioManager.Instance.init();
        // this.testVersion.string = this.clientTestVersion;

        // cc.director.loadScene("GameScene");

        // cc.director.preloadScene("GameScene", ()=>{
        //     // debugger;
         
        // })
    }

    //判断来源
    containsTrain(str) {
    
        return /from=train/i.test(str);
    }

    //开始游戏，跳转至引导页面
    startGame(){
        cc.director.loadScene("GameScene");
        // cc.director.loadScene("GuideScene");
    }
    //备用，用来测试跳转 指定关卡
    clickBtn(event,data){
        cc.fx.GameConfig.GM_INFO.custom = parseInt(data);
        cc.director.loadScene("GameScene");
    }   
    //打开排行榜
    openRank(){
        cc.director.loadScene("RankScene");
    }

    
    protected update(dt: number): void {
    }
    
//     3月17日 - 3月21日 工作完成内容

// 1：游戏框架搭建
// 2：制作18个基础方块预制体 (方块可编辑颜色与道具和状态)
// 3：完成地图的搭建，可配置8*8以内，任意组合，包括可缺口和障碍物配置
// 4：完成地图墙面建立，根据 ↑3上面构建的地图自动生成墙体。
// 5：做完方块的基础移动，跟随手指，遇到方块或者墙壁或者障碍物阻碍移动。
// 6：方块的自动落点做完11个基础方块的（未做完还差11个）

// 3月24日 - 3月28日 预计完成目标

// 1：完成全部方块的落点。
// 2：完成门的搭建，门可选颜色，可选开关或者星星等特殊状态
// 3：完成方块通过门的游戏逻辑，使游戏可以最基础运行玩起来
// 4：出5关版本，配合小白备案审核。
// 5：根据方块，地图，以及道具，制作地图编辑器 (方块和地图制作的时候都已经考虑到编辑器的需求了) 
// 	优先制作，后续开发拓展玩法功能时，小白可同步进行制作关卡。
}
