
// cc.Class({
//     extends: cc.Component,
//     properties: {
//         localTest: {
//             default: false,
//             tooltip: '本地测试时勾选，避免tz_url和Configure报错，提交前勾掉'
//         },
//         clientTest: {
//             default: false,
//             tooltip: '客户端测试时勾选，展示版本标记方便测试区分，上线前勾掉'
//         },
//         clientTestVersion: {
//             default: '',
//             tooltip: '版本标记'
//         },
//         testVersion: cc.Label,
//         score: cc.Label,
//         double_hit: cc.Node,
//         add: cc.Node,
//         add2: cc.Node,
//         double_title: cc.Node,
//         count_time: cc.Node,
//         beginNode: cc.Node,
//         ball_nomal: [cc.SpriteFrame],
//         bg_nomal: [cc.SpriteFrame],
//         ball_light: [cc.SpriteFrame],
//         kuang_Frame: [cc.SpriteFrame],
//         daojishi: cc.Label,
//         pause_anniu: cc.Sprite,
//         mask: cc.Node,

//         flashUI: {
//             default: null,
//             type: cc.SpriteAtlas
//         },
//     },

//     onLoad() {


//     },

//     update(dt) {

//     },

// });